config/routes.rb
Official::Application.routes.draw do

  resources :home do
    collection do
      get "guide"
      get "list", :as => :history
    end
  end

  match '/guide' => "home#guide", :as => :guide
  match '/list' => "home#history", :as => :history

  root :to => "home#index"

end

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title 首页
    = include_gon
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = yield(:page_include_scripts) if content_for?(:page_include_scripts)

    = csrf_meta_tags

    = yield(:page_include_css) if content_for?(:page_include_css)
    = yield(:page_inline_css) if content_for?(:page_inline_css)
    = yield(:page_inline_scripts) if content_for?(:page_inline_scripts)


  %body
    #overmain
      #header
        %p.domain http://www.cj-10.tw
      %table.tabmain{:align => "center", :cellpadding => "0", :cellspacing => "0"}
        %tbody
          %tr
            %td.td-left{:valign => "top", :width => "200"}
              #leftarea
                #leftmenu
                  %ul
                    %li
                      = link_to root_path do
                        = image_tag "menu_01.jpg", :alt => "精彩十分网站首页", :border => "0"
                    %li
                      = link_to guide_path do
                        = image_tag "menu_02.jpg", :alt => "精彩十分彩购指南", :border => "0"
                    %li
                      = link_to history_path do
                        = image_tag "menu_09.jpg", :alt => "精彩十分开奖记录", :border => "0"
                    %li
                      %a{:href => "/certificate.asp"}
                        = image_tag "menu_08.jpg", :alt => "精彩十分授权证书", :border => "0"
                #leftlist
                  %dl
                    %dt 开奖日期
                    %dd
                      #tip www.jc-10.tw從早上10點開始到零晨2點結束.每10分鍾就開獎一期,共開108期. 閣下如獲中獎金超過五百萬，請於三十個工作日內登記。
                      #attention
                    %dd.boot
            %td.td-middle{:valign => "top", :width => "10"}
            %td.td-right{:valign => "top", :width => 590}
              = yield

      #boot-ad
        %ul
          %li.left-space
          %li.mid-info
            = image_tag "ad_01.gif", :alt => "精彩十分公司总部大楼"
          %li.right-space

      #footer
        %ul
          %li.left-space
          %li.mid-info
            Copyright 2009-2010 Powered by&nbsp;
            = succeed "\u{53d1}\u{884c}\u{7ba1}\u{7406}\u{4e2d}\u{5fc3}\u{552f}\u{4e00}\u{6307}\u{5b9a}\u{5b98}\u{65b9}\u{7f51}\u{7ad9}" do
              %a{:href => "http://www.twjhc.com/", :target => "_blank", :title => "精彩十分公司"} 精彩十分公司
            \&nbsp;&nbsp;请勿转载&nbsp;&nbsp;联系邮箱:
            %a{:href => "mailto:nike@twjhc.com"} nike@twjhc.com
          %li.right-space

app/views/layouts/application2.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title 首页
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .all
      .wrapper
        / 头部开始
        .header
          .headerleft
        .clear
        .nav
          .nav1
            %ul
              %li
                %a{:href => "#"} 開獎專區
              %li
                %a{:href => "#"} 新聞專區
              %li
                %a{:href => "#"} 經銷商專區
              %li
                %a{:href => "#"} 常見問題
              %li
                %a{:href => "#"} 銷售于兌獎
              %li
                %a{:href => "#"} 愛心公益
              %li
                %a{:href => "#"} 聯繫我們
        .clear
        / 头部结束
        .contentbg
          .content
            .content_top
              .content_top_case
                %p 體彩福彩
                %p 六和彩
                %p 3D彩
            .content_min
              %a{:href => "#"} 精彩十分開獎
              %a{:href => "#"} 精彩十分開獎時間
              %a{:href => "#"} 台精彩十分开獎公告
              %a{:href => "#"} 精彩十分開獎結果
              %a{:href => "#"} 精彩十分歷史開獎
              %a{:href => "#"} 精彩十分技巧
              %a{:href => "#"} 精彩十分圖標走勢
              %a{:href => "#"} 精彩十分規則
        = yield

      / 底部开始
      .footer
        .footer1
      .clear
      / 底部结束